// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type SearchResponse struct {
	Results              []*SearchResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Modified             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=modified,proto3" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() []*SearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchResponse) GetModified() *timestamp.Timestamp {
	if m != nil {
		return m.Modified
	}
	return nil
}

type SearchResult struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResult) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*SearchResult)(nil), "SearchResult")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x6b, 0xb4, 0x30,
	0x10, 0x86, 0x51, 0xd9, 0xef, 0xab, 0x63, 0xb5, 0x25, 0xf4, 0x20, 0x7b, 0x59, 0xf1, 0xd0, 0x7a,
	0x72, 0x61, 0x0b, 0xfd, 0x19, 0x65, 0x49, 0x7b, 0x17, 0x5d, 0x67, 0x6d, 0x40, 0x4d, 0xcc, 0x24,
	0x87, 0xfe, 0xfb, 0x62, 0x82, 0xcb, 0xde, 0x32, 0xef, 0x3c, 0xcc, 0x9b, 0x07, 0xb2, 0x09, 0x89,
	0xda, 0x01, 0xa9, 0x56, 0x5a, 0x1a, 0xb9, 0x3f, 0x0c, 0x52, 0x0e, 0x23, 0x1e, 0xdd, 0xd4, 0xd9,
	0xeb, 0xd1, 0x88, 0x09, 0xc9, 0xb4, 0x93, 0xf2, 0x40, 0x39, 0x43, 0xfa, 0x85, 0xad, 0xbe, 0xfc,
	0x70, 0x5c, 0x2c, 0x92, 0x61, 0x2f, 0xb0, 0x5b, 0x2c, 0xea, 0xdf, 0x3c, 0x28, 0x82, 0x2a, 0xe6,
	0x7e, 0x60, 0x07, 0x48, 0x54, 0x3b, 0x60, 0x33, 0xdb, 0xa9, 0x43, 0x9d, 0x87, 0x45, 0x50, 0xed,
	0x38, 0xac, 0xd1, 0xa7, 0x4b, 0xd8, 0x2b, 0x3c, 0x69, 0x24, 0x3b, 0x9a, 0x46, 0xa1, 0x6e, 0xd6,
	0x45, 0x1e, 0x39, 0x28, 0xf5, 0xf1, 0x19, 0xf5, 0xb9, 0x1d, 0xb0, 0x5c, 0x20, 0xdb, 0xfa, 0x48,
	0xc9, 0x99, 0x90, 0xbd, 0xc1, 0x7f, 0x8f, 0x50, 0x1e, 0x14, 0x51, 0x95, 0x9c, 0xd2, 0xfa, 0x46,
	0xd8, 0xd1, 0xf0, 0x6d, 0xcb, 0x3e, 0xe0, 0x61, 0x92, 0xbd, 0xb8, 0x0a, 0xec, 0xdd, 0x07, 0x92,
	0xd3, 0xbe, 0xf6, 0x7a, 0xf5, 0xa6, 0x57, 0x7f, 0x6f, 0x7a, 0xfc, 0xc6, 0x96, 0x1c, 0x1e, 0xef,
	0x0f, 0xb2, 0x0c, 0x42, 0xd1, 0x3b, 0xbd, 0x88, 0x87, 0xa2, 0x67, 0xcf, 0x10, 0x59, 0x3d, 0xba,
	0x93, 0x31, 0x5f, 0x9f, 0xac, 0x80, 0xa4, 0x47, 0xba, 0x68, 0xa1, 0x8c, 0x90, 0xb3, 0x13, 0x89,
	0xf9, 0x7d, 0xd4, 0xfd, 0x73, 0x8d, 0xef, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x94, 0xf0,
	0x59, 0x70, 0x01, 0x00, 0x00,
}
