// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphdata

type NewEdge struct {
	Parent string `json:"parent"`
	Child  string `json:"child"`
}

type NewNode struct {
	ID     string  `json:"id"`
	Parent *string `json:"parent"`
}
