// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type Address struct {
	Address1 string `json:"address1"`
	Address2 string `json:"address2"`
	Address3 string `json:"address3"`
	Address4 string `json:"address4"`
	Postcode string `json:"postcode"`
	Country  string `json:"country"`
}

type Company struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	VatNumber string  `json:"vatNumber"`
	Address   Address `json:"address"`
}

type Item struct {
	ID    string `json:"id"`
	Desc  string `json:"desc"`
	Price int    `json:"price"`
}

type NewCompany struct {
	Name      string            `json:"name"`
	VatNumber string            `json:"vatNumber"`
	Address   NewCompanyAddress `json:"address"`
}

type NewCompanyAddress struct {
	Address1 string `json:"address1"`
	Address2 string `json:"address2"`
	Address3 string `json:"address3"`
	Address4 string `json:"address4"`
	Postcode string `json:"postcode"`
	Country  string `json:"country"`
}

type NewOrder struct {
	Items []string `json:"items"`
}
